apiVersion: v1
kind: Service
metadata:
  name: my-service2
  labels:
    app: helloapp2
spec:
  type: LoadBalancer
  selector:
    app: helloapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment2
  labels:
    app: helloapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloapp2
  template:
    metadata:
      labels:
        app: helloapp2
    spec:
      containers:
      - name: codecatalyst-eks-container
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
        image: rushidockerhub1881/helloapp2:latest
        ports:
        - containerPort: 80
